version: '3.7'

services:
  server:
    build:
      context: ./server/
    command: npm run dev
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - /app/node_modules

  client:
    build:
      context: ./client/
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - server