name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test client
        run: |
          cd ./client
          npm install
          npm run test
        env:
          NODE_ENV: development
          PORT: 8080
          LOG_FORMAT: combined
          LOG_DIR: ./logs

      - name: Test server
        run: |
          cd ./server
          npm install
          npm run test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run
        run: |
          docker-compose build
          docker-compose up
