name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test client
        run: |
          cd ./client
          npm run test

      - name: Test server
        run: |
          cd ./surver
          npm run test
